repos:
  - repo: https://github.com/diffplug/spotless
    rev: '2.44.0' # Utiliza la última versión estable
    hooks:
      - id: spotless
        name: Spotless
        entry: mvn spotless:apply
        language: system
        pass_filenames: false
        stages: [ pre-commit ]

      - id: checkstyle
        name: Checkstyle
        entry: mvn checkstyle:check
        language: system
        pass_filenames: false
        stages: [ pre-commit ]

      - id: test
        name: Tests
        entry: mvn test
        language: system
        pass_filenames: false
        stages: [ pre-commit ]
